pluginName = Built-In Script Language for project extension ui
providerName = 1C-Soft LLC

command.description.0 = Create method extension handler
command.name.0 = Add to Extension
command.tooltip.0 = Create method extension handler
action.label.0 = Add to Extension
