#Configuration File
#Fri Jun 12 11:24:07 MSK 2026
osgi.splashPath=file\:C\:/VC/EDT-plugin-WS/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/plugins/org.eclipse.sdk_4.30.0.v20231201-0110
osgi.bundles=reference\:file\:C\:/VC/EDT-plugin-WS/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/plugins/org.eclipse.equinox.simpleconfigurator_1.5.0.v20230919-1457.jar@1\:start
osgi.install.area=file\:C\:\\VC\\EDT-plugin-WS\\.metadata\\.plugins\\org.eclipse.pde.core\\.bundle_pool
org.eclipse.equinox.simpleconfigurator.configUrl=file\:/C\:/VC/EDT-plugin-WS/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/org.eclipse.equinox.simpleconfigurator/bundles.info
eclipse.p2.data.area=@config.dir/.p2
osgi.bundles.defaultStartLevel=4
eclipse.p2.profile=SelfHostingProfile
osgi.framework=file\:C\:/VC/EDT-plugin-WS/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/plugins/org.eclipse.osgi_3.18.600.v20231110-1900.jar
osgi.configuration.cascaded=false
org.eclipse.update.reconcile=false
