#
#Вс окт 04 18:41:55 MSK 2026
tormozit.comfort;1.0.1.7-qualifier=bin,lib/jacob.jar
tormozit.comfort.checks;1.0.2=bin
tormozit.comfort.bslparser;1.0.1.qualifier=bin
@ignoredot@=true
tormozit.comfort=bin,lib/jacob.jar
tormozit.comfort.checks=bin
tormozit.comfort.bslparser=bin
